version: '2'

services:
  app:
    build:
      context: .
    volumes:
        - .:/app
    working_dir: /app
    command: python /app/manage.py runserver
    ports:
        - "8000:8000"
  mysql:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    volumes:
        - ./data/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
